export const mockCloudData = {
  totalSpend: 127450.5,
  monthlySpend: 82230.75,
  forecastedSpend: 91800.25,
  forecastedAnnual: 1101603.0,
  savings: 18503.0,
  totalSavingsYTD: 45230.75,
  optimizationPotential: 24500.0,
  costPerEmployee: 485.5,
  providers: {
    AWS: { spend: 62100.5, percentage: 48.7, trend: "up", trend_value: 2.3 },
    Azure: { spend: 35450.25, percentage: 27.8, trend: "down", trend_value: -1.2 },
    GCP: { spend: 29899.75, percentage: 23.5, trend: "up", trend_value: 5.8 },
  },
  dailySpend: [
    { date: "Jan 10", AWS: 1800, Azure: 1200, GCP: 950, total: 3950 },
    { date: "Jan 11", AWS: 1950, Azure: 1150, GCP: 1100, total: 4200 },
    { date: "Jan 12", AWS: 2100, Azure: 1300, GCP: 1050, total: 4450 },
    { date: "Jan 13", AWS: 2200, Azure: 1250, GCP: 1150, total: 4600 },
    { date: "Jan 14", AWS: 2400, Azure: 1400, GCP: 1200, total: 5000 },
    { date: "Jan 15", AWS: 2350, Azure: 1350, GCP: 1250, total: 4950 },
    { date: "Jan 16", AWS: 2500, Azure: 1450, GCP: 1300, total: 5250 },
  ],
  services: [
    { name: "EC2 Instances", cost: 24000, percentage: 18.8, region: "us-east-1", risk: "high", trend: "up" },
    { name: "RDS Database", cost: 18000, percentage: 14.1, region: "eu-west-1", risk: "medium", trend: "stable" },
    { name: "S3 Storage", cost: 6500, percentage: 5.1, region: "us-west-2", risk: "low", trend: "down" },
    { name: "Lambda", cost: 3200, percentage: 2.5, region: "us-east-1", risk: "low", trend: "up" },
    { name: "CloudFront", cost: 9800, percentage: 7.7, region: "global", risk: "medium", trend: "stable" },
    { name: "ECS Containers", cost: 15600, percentage: 12.2, region: "us-east-1", risk: "medium", trend: "up" },
    { name: "NAT Gateway", cost: 8900, percentage: 7.0, region: "us-east-1", risk: "high", trend: "up" },
    { name: "Data Transfer", cost: 12450, percentage: 9.8, region: "global", risk: "high", trend: "up" },
  ],
  anomalies: [
    {
      id: 1,
      title: "Spike in EC2 Instances",
      severity: "high",
      timestamp: "2 hours ago",
      details: "Unusual 45% increase in compute costs detected",
      cost_impact: 1250,
      recommendation: "Scale down over-provisioned instances",
    },
    {
      id: 2,
      title: "Idle RDS Instance",
      severity: "medium",
      timestamp: "6 hours ago",
      details: "Database running without queries for 12 hours",
      cost_impact: 450,
      recommendation: "Consider data migration or instance shutdown",
    },
    {
      id: 3,
      title: "Data Transfer Surge",
      severity: "high",
      timestamp: "1 day ago",
      details: "Unexpected 2.5x bandwidth usage increase",
      cost_impact: 2100,
      recommendation: "Implement CloudFront caching or CDN optimization",
    },
  ],
  forecast: [
    { month: "Jan", projected: 82000, confidence_upper: 88000, confidence_lower: 76000 },
    { month: "Feb", projected: 85000, confidence_upper: 92000, confidence_lower: 78000 },
    { month: "Mar", projected: 89000, confidence_upper: 97000, confidence_lower: 81000 },
    { month: "Apr", projected: 87000, confidence_upper: 95000, confidence_lower: 79000 },
    { month: "May", projected: 91000, confidence_upper: 99000, confidence_lower: 83000 },
    { month: "Jun", projected: 93000, confidence_upper: 101000, confidence_lower: 85000 },
    { month: "Jul", projected: 95000, confidence_upper: 103000, confidence_lower: 87000 },
    { month: "Aug", projected: 94000, confidence_upper: 102000, confidence_lower: 86000 },
    { month: "Sep", projected: 96000, confidence_upper: 104000, confidence_lower: 88000 },
    { month: "Oct", projected: 98000, confidence_upper: 106000, confidence_lower: 90000 },
    { month: "Nov", projected: 100000, confidence_upper: 108000, confidence_lower: 92000 },
    { month: "Dec", projected: 102000, confidence_upper: 110000, confidence_lower: 94000 },
  ],
  autonomousDecisions: [
    {
      id: "OPT-2847",
      timestamp: "2025-01-17T14:30:00Z",
      action: "SPOT_MIGRATE",
      resource: "dev-environment",
      savings: 1742.42,
      confidence: 91,
      status: "completed" as const,
    },
    {
      id: "OPT-2848",
      timestamp: "2025-01-17T10:15:00Z",
      action: "RIGHT_SIZE",
      resource: "prod-api-cluster",
      savings: 1401.58,
      confidence: 90,
      status: "completed" as const,
    },
    {
      id: "OPT-2849",
      timestamp: "2025-01-17T08:45:00Z",
      action: "RIGHT_SIZE",
      resource: "analytics-db-primary",
      savings: 1086.84,
      confidence: 94,
      status: "pending" as const,
    },
    {
      id: "OPT-2850",
      timestamp: "2025-01-16T22:10:00Z",
      action: "RIGHT_SIZE",
      resource: "prod-api-cluster",
      savings: 792.15,
      confidence: 89,
      status: "completed" as const,
    },
  ],
  costTrajectory: [
    { date: "Jan 12", baseline: 82000, forecast: 82000, optimized: 82000 },
    { date: "Jan 13", baseline: 84500, forecast: 84000, optimized: 78900 },
    { date: "Jan 14", baseline: 87000, forecast: 86500, optimized: 76200 },
    { date: "Jan 15", baseline: 89500, forecast: 89000, optimized: 74500 },
    { date: "Jan 16", baseline: 92000, forecast: 91500, optimized: 73100 },
    { date: "Jan 17", baseline: 95000, forecast: 94000, optimized: 71800 },
    { date: "Feb", baseline: 98000, forecast: 97000, optimized: 70500 },
    { date: "Mar", baseline: 101000, forecast: 100000, optimized: 69200 },
    { date: "Apr", baseline: 103000, forecast: 102000, optimized: 68100 },
    { date: "May", baseline: 106000, forecast: 105000, optimized: 67000 },
    { date: "Jun", baseline: 109000, forecast: 108000, optimized: 65900 },
  ],
  todayImpact: {
    decisions_made: 999,
    decisions_unit: "Auto-triggered actions",
    avg_latency: "31ms",
    latency_unit: "Decision time",
    resources_managed: 1391,
    resources_unit: "Under management",
    data_processed: "3.2TB",
    data_unit: "Processed today",
  },
  simulatorPresets: [
    {
      name: "Conservative",
      ec2_instances: 120,
      reserved_instances: 80,
      spot_instances: 40,
      estimated_savings: 15000,
    },
    {
      name: "Aggressive",
      ec2_instances: 80,
      reserved_instances: 120,
      spot_instances: 80,
      estimated_savings: 28000,
    },
    {
      name: "Balanced",
      ec2_instances: 100,
      reserved_instances: 100,
      spot_instances: 60,
      estimated_savings: 21000,
    },
  ],
  infrastructureTopology: {
    regions: [
      { name: "us-east-1", resources: 245, spend: 28500, utilization: 78 },
      { name: "eu-west-1", resources: 156, spend: 18200, utilization: 65 },
      { name: "ap-southeast-1", resources: 89, spend: 12100, utilization: 72 },
    ],
    services: [
      { type: "compute", count: 340, spend: 42000 },
      { type: "storage", count: 156, spend: 8900 },
      { type: "database", count: 78, spend: 15200 },
      { type: "networking", count: 234, spend: 18500 },
    ],
  },
}

export const recommendations = [
  {
    id: 1,
    title: "Right-size EC2 instances",
    savings: 4500,
    effort: "low",
    impact: "high",
    riskReduction: 15,
    estimatedImplementation: "2 hours",
    confidence: 92,
  },
  {
    id: 2,
    title: "Convert to Reserved Instances",
    savings: 12000,
    effort: "medium",
    impact: "high",
    riskReduction: 8,
    estimatedImplementation: "1 day",
    confidence: 85,
  },
  {
    id: 3,
    title: "Consolidate databases",
    savings: 3200,
    effort: "high",
    impact: "medium",
    riskReduction: 20,
    estimatedImplementation: "3 days",
    confidence: 78,
  },
  {
    id: 4,
    title: "Enable S3 Intelligent-Tiering",
    savings: 2100,
    effort: "low",
    impact: "medium",
    riskReduction: 5,
    estimatedImplementation: "30 minutes",
    confidence: 88,
  },
  {
    id: 5,
    title: "Remove unattached EBS volumes",
    savings: 850,
    effort: "low",
    impact: "low",
    riskReduction: 10,
    estimatedImplementation: "15 minutes",
    confidence: 95,
  },
]

// AWS All Regions
export const AWS_REGIONS = [
  "us-east-1 (N. Virginia)",
  "us-east-2 (Ohio)",
  "us-west-1 (N. California)",
  "us-west-2 (Oregon)",
  "eu-west-1 (Ireland)",
  "eu-west-2 (London)",
  "eu-west-3 (Paris)",
  "eu-central-1 (Frankfurt)",
  "eu-north-1 (Stockholm)",
  "ap-northeast-1 (Tokyo)",
  "ap-northeast-2 (Seoul)",
  "ap-northeast-3 (Osaka)",
  "ap-southeast-1 (Singapore)",
  "ap-southeast-2 (Sydney)",
  "ap-south-1 (Mumbai)",
  "ca-central-1 (Canada)",
  "sa-east-1 (São Paulo)",
  "me-south-1 (Bahrain)",
  "af-south-1 (Cape Town)",
]

// Azure All Regions
export const AZURE_REGIONS = [
  "eastus (Virginia)",
  "eastus2 (Virginia)",
  "westus (California)",
  "westus2 (Washington)",
  "westus3 (Phoenix)",
  "westeurope (Netherlands)",
  "northeurope (Ireland)",
  "uksouth (London)",
  "ukwest (Wales)",
  "francecentral (Paris)",
  "francesouth (Marseille)",
  "germanywestcentral (Frankfurt)",
  "germanynorth (Berlin)",
  "switzerlandnorth (Zurich)",
  "switzerlandwest (Geneva)",
  "norvegeneast (Norway)",
  "norwegiawest (Norway)",
  "southafricanorth (South Africa)",
  "southafricawest (South Africa)",
  "japaneast (Tokyo)",
  "japanwest (Osaka)",
  "koreacentral (Seoul)",
  "koreasouth (Busan)",
  "southeastasia (Singapore)",
  "eastasia (Hong Kong)",
  "australiaeast (Sydney)",
  "australiasoutheast (Melbourne)",
  "centralindia (Pune)",
  "southindia (Chennai)",
  "westindia (Mumbai)",
  "canadacentral (Toronto)",
  "canadaeast (Quebec)",
  "brazilsouth (São Paulo)",
  "brasiliasoutheast (Rio de Janeiro)",
  "uaecentral (Abu Dhabi)",
  "uaenorth (Dubai)",
]

// GCP All Regions
export const GCP_REGIONS = [
  "us-central1 (Iowa)",
  "us-east1 (South Carolina)",
  "us-east4 (Virginia)",
  "us-west1 (Oregon)",
  "us-west2 (Los Angeles)",
  "us-west3 (Salt Lake City)",
  "us-west4 (Las Vegas)",
  "us-south1 (Dallas)",
  "northamerica-northeast1 (Montreal)",
  "northamerica-northeast2 (Toronto)",
  "southamerica-east1 (São Paulo)",
  "southamerica-west1 (Santiago)",
  "europe-west1 (Belgium)",
  "europe-west2 (London)",
  "europe-west3 (Frankfurt)",
  "europe-west4 (Netherlands)",
  "europe-west6 (Zurich)",
  "europe-north1 (Finland)",
  "europe-southwest1 (Madrid)",
  "asia-east1 (Taiwan)",
  "asia-east2 (Hong Kong)",
  "asia-northeast1 (Tokyo)",
  "asia-northeast2 (Osaka)",
  "asia-northeast3 (Seoul)",
  "asia-south1 (Delhi)",
  "asia-south2 (Mumbai)",
  "asia-southeast1 (Singapore)",
  "asia-southeast2 (Jakarta)",
  "australia-southeast1 (Sydney)",
  "australia-southeast2 (Melbourne)",
  "me-west1 (Tel Aviv)",
  "me-central1 (Doha)",
  "me-central2 (Dammam)",
  "af-south1 (South Africa)",
]

export const CLOUD_SERVICES = {
  AWS: ["EC2", "RDS", "S3", "Lambda", "CloudFront", "ECS", "EKS", "Redshift", "DynamoDB", "DocumentDB"],
  Azure: [
    "Virtual Machines",
    "App Service",
    "SQL Database",
    "Cosmos DB",
    "Blob Storage",
    "Container Instances",
    "Kubernetes Service",
    "Azure Synapse",
    "Data Lake",
    "Application Gateway",
  ],
  GCP: [
    "Compute Engine",
    "Cloud SQL",
    "Cloud Storage",
    "Cloud Functions",
    "Cloud CDN",
    "GKE",
    "BigQuery",
    "Dataflow",
    "Cloud Bigtable",
    "Pub/Sub",
  ],
}
